main: com.eznetherite.uselessupgradetemplate.UselessUpgradeTemplate
name: UselessUpgradeTemplate
version: "1.0.0"
api-version: "26.1"
author: [break08]
description: Get Netherite stuff without Upgrade Template
folia-supported: true